poetry init

[tool.poetry]
name = "transfer-tracker-api"
version = "0.1.0"
description = ""
authors = ["Your Name <your@email.com>"]

[tool.poetry.dependencies]
python = "^3.9"
flask = "^2.0"
requests = "^2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

git add pyproject.toml
git commit -m "Add pyproject.toml for Poetry"
git push
