services:
  - type: web
    name: transfer-tracker
    env: python
    plan: free
    buildCommand: |
      pip install poetry
      poetry config virtualenvs.create false
      poetry install
    startCommand: gunicorn app:app  # or python app.py
    envVars:
      - key: NEWS_API_KEY
        value: "df28d02564c64ca891c9e91da26e32fa"

