services:
  - type: web
    name: flask-app
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: NEWS_API_KEY
        value: df28d02564c64ca891c9e91da26e32fa
