name: Update Player Names

on:
  workflow_dispatch:      # Manual trigger
  schedule:
    - cron: '0 6 * * 1'   # Every Monday at 06:00 UTC

jobs:
  update-players:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install remotes + worldfootballR from GitHub using PAT
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}
        run: |
          Rscript -e '
            if (!require("remotes")) install.packages("remotes", repos = "https://cloud.r-project.org")
            remotes::install_github("JaseZiv/worldfootballR")
          '

      - name: Run generate_player_names.R
        run: Rscript generate_player_names.R

      - name: Commit updated player names
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add player_names.txt
          git commit -m "⬆️ Auto-update player_names.txt" || echo "No changes to commit"
          git push
