name: Update Player Names

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  update-players:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/YOUR_USERNAME/player-names:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run generate_player_names.R (from container)
        run: |
          cp player_names.txt ./player_names.txt

      - name: Commit player_names.txt
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add player_names.txt
          git commit -m "⬆️ Auto-update player_names.txt" || echo "No changes"
          git push
