name: Update Player List Weekly

on:
  schedule:
    - cron: '0 6 * * 1'  # Every Monday at 6:00 UTC
  workflow_dispatch:

jobs:
  update-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages and generate player list
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}
        run: |
          Rscript -e "
            install.packages('remotes', repos = 'http://cran.us.r-project.org');
            remotes::install_github('JaseZiv/worldfootballR');
            install.packages(c('dplyr', 'readr', 'purrr'), repos = 'http://cran.us.r-project.org');
            source('generate_player_list.R');
          "

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add player_names.txt
          git commit -m "Update player list [auto]" || echo "No changes to commit"
          git push
