name: Update Player Names

on:
  schedule:
    - cron: '0 6 1 * *'  # 1st of every month at 06:00 UTC
  workflow_dispatch:

jobs:
  update-players:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install beautifulsoup4 requests

      - name: Run player name scraper
        run: python generate_player_names.py

      - name: Commit updated player names
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add player_names.txt
          git commit -m "⬆️ Monthly update of player_names.txt" || echo "No changes"
          git push
