name: Update Player Names

on:
  schedule:
    - cron: '0 6 1 * *'  # Run at 06:00 UTC on the 1st of each month
  workflow_dispatch:

jobs:
  update-players:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install scraping dependencies
        run: pip install beautifulsoup4 cloudscraper

      - name: Run player name scraper
        run: python generate_player_names.py

            - name: Commit updated player-position-club.txt
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add player-position-club.txt
          git commit -m "⬆️ Monthly update of player-position-club.txt" || echo "No changes"
          git push
