name: Update Player Names

on:
  workflow_dispatch:      # Manual trigger
  schedule:
    - cron: '0 6 * * 1'   # Every Monday at 06:00 UTC

jobs:
  update-players:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/YOUR_USERNAME/player-names:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run generate_player_names.R inside container
        run: Rscript /usr/local/src/generate_player_names.R

      - name: Commit updated player names
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add player_names.txt
          git commit -m "⬆️ Auto-update player_names.txt" || echo "No changes"
          git push
