name: Update Player Names

on:
  workflow_dispatch:      # Manual trigger
  schedule:
    - cron: '0 6 * * 1'   # Every Monday at 06:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies & run script
        run: |
          Rscript generate_player_names.R

      - name: Commit updated player names
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add player_names.txt
          git commit -m "⬆️ Auto-update player_names.txt"
          git push
