name: Update Player Names

on:
  schedule:
    - cron: '0 6 * * 1'  # Runs every Monday at 6:00 UTC
  workflow_dispatch:     # Allows you to trigger it manually from GitHub

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-root

      - name: Run player name generator
        run: python generate_player_names.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add player_names.txt
          git commit -m "⬆️ Auto-update player_names.txt [bot]" || echo "No changes to commit"
          git push
